"""生成无反射、只读配置 class。"""
from pathlib import Path
from .schema_hash import schema_hash

CS_TYPES = {"uint":"uint", "int":"int", "bool":"bool", "float":"float", "long":"long", "double":"double", "string":"string", "bytes":"byte[]", "byte":"byte", "sbyte":"sbyte", "short":"short", "ushort":"ushort", "ulong":"ulong"}
READERS = {"uint":"ReadUInt32", "int":"ReadInt32", "bool":"ReadBoolean", "float":"ReadSingle", "long":"ReadInt64", "double":"ReadDouble", "string":"ReadString", "bytes":"ReadBytes", "byte":"ReadByte", "sbyte":"ReadSByte", "short":"ReadInt16", "ushort":"ReadUInt16", "ulong":"ReadUInt64"}

def _type(t):
    if t in CS_TYPES: return CS_TYPES[t]
    if t.endswith("[]"): return _type(t[:-2]) + "[]"
    if t.startswith("List<"): return "List<" + _type(t[5:-1]) + ">"
    return t

def _read(t):
    if t in READERS: return f"reader.{READERS[t]}()"
    raise ValueError(f"暂不支持生成集合字段：{t}")

def generate(config, output):
    hash_bytes, hash_hex = schema_hash(config)
    lines = ["// <auto-generated />", "using System;", "using GameProto;", "", f"namespace GameProto.Config.Generated_{config.name}", "{", f"    public sealed class {config.class_name}", "    {"]
    for field in config.fields: lines.append(f"        public {_type(field.type_name)} {field.name} {{ get; }}")
    lines += ["", f"        public {config.class_name}({', '.join(_type(f.type_name) + ' ' + f.name[0].lower() + f.name[1:] for f in config.fields)})", "        {"]
    for field in config.fields: lines.append(f"            {field.name} = {field.name[0].lower() + field.name[1:]};")
    lines += ["        }", "", f"        public static {config.class_name} Decode(ref ProtoReader reader)", "        {"]
    for field in config.fields: lines.append(f"            {_type(field.type_name)} {field.name[0].lower() + field.name[1:]} = {_read(field.type_name)};")
    args = ", ".join(f.name[0].lower() + f.name[1:] for f in config.fields)
    lines += [f"            return new {config.class_name}({args});", "        }", "", f"        public const ulong SchemaHash = 0x{int.from_bytes(hash_bytes, 'little'):016X}UL;", "    }", "}", ""]
    text = "\n".join(lines)
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not destination.exists() or destination.read_text(encoding="utf-8") != text: destination.write_text(text, encoding="utf-8", newline="\n")
    return hash_hex

def generate_table(config, output):
    """在 GameLogic 中生成配置数据表容器，依赖 GameProto 中的记录类。"""
    lines = [
        "// <auto-generated />", "using System;", "using System.Collections.Generic;", "using GameProto;",
        f"using GameProto.Config.Generated_{config.name};", "", f"namespace GameLogic.Config.Generated_{config.name}", "{",
        f"    public sealed class {config.class_name}Table", "    {", f"        private readonly Dictionary<int, {config.class_name}> _items;",
        "", "        public int Count => _items.Count;", "", f"        private {config.class_name}Table(Dictionary<int, {config.class_name}> items)", "        {", "            _items = items;", "        }", "",
        f"        public bool TryGet(int id, out {config.class_name} config)", "        {", "            return _items.TryGetValue(id, out config);", "        }", "",
        f"        public {config.class_name} Get(int id)", "        {", "            if (!_items.TryGetValue(id, out var config))", "            {", "                throw new KeyNotFoundException($\"找不到 {config.class_name} 配置：{id}\");", "            }", "", "            return config;", "        }", "",
        f"        public static {config.class_name}Table Load(byte[] data)", "        {", "            if (data == null)", "            {", "                throw new ArgumentNullException(nameof(data));", "            }", "", "            var reader = new ProtoReader(data);", "            ConfigFileHeader header = ConfigFileHeader.Decode(ref reader);", f"            if (header.SchemaHash != {config.class_name}.SchemaHash)", "            {", "                throw new ConfigSerializationException(\"配置 Schema Hash 不匹配。\");", "            }", "", "            if (header.RecordCount > int.MaxValue)", "            {", "                throw new ConfigSerializationException(\"配置记录数超出 int 范围。\");", "            }", "", f"            var items = new Dictionary<int, {config.class_name}>((int)header.RecordCount);", "            for (int i = 0; i < header.RecordCount; i++)", "            {", f"                {config.class_name} item = {config.class_name}.Decode(ref reader);", "                int key = item.Id;", "                if (items.ContainsKey(key))", "                {", "                    throw new ConfigSerializationException($\"配置主键重复：{key}。\");", "                }", "", "                items.Add(key, item);", "            }", "", "            reader.EnsureFullyConsumed();", f"            return new {config.class_name}Table(items);", "        }", "    }", "}", ""
    ]
    text = "\n".join(lines)
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not destination.exists() or destination.read_text(encoding="utf-8") != text:
        destination.write_text(text, encoding="utf-8", newline="\n")
