using System.Buffers.Binary;
using System.Text;

namespace ConfigTableGenerator;

internal static class SourceGenerator
{
    public static string GenerateClientRecord(ConfigOutputModel model, string rootNamespace)
    {
        string namespaceName = $"{rootNamespace}.{Sanitize(model.SheetName)}";
        StringBuilder code = Header();
        code.AppendLine("using System.Collections.Generic;").AppendLine("using GameProto;").AppendLine();
        code.AppendLine($"namespace {namespaceName}").AppendLine("{");
        AppendCSharpCustomTypes(code, model.Fields);
        code.AppendLine($"    public sealed class {model.ClassName} : ConfigRecord").AppendLine("    {");
        foreach (LogicalField field in model.Fields) code.AppendLine($"        public {CSharpType(field.Type)} {field.Name} {{ get; }}");
        code.AppendLine().AppendLine($"        public const ulong SchemaHash = 0x{SchemaHashValue(model):X16}UL;");
        code.AppendLine().AppendLine($"        public {model.ClassName}({string.Join(", ", model.Fields.Select(field => $"{CSharpType(field.Type)} {Camel(field.Name)}"))})").AppendLine("        {");
        foreach (LogicalField field in model.Fields) code.AppendLine($"            {field.Name} = {Camel(field.Name)};");
        code.AppendLine("        }").AppendLine().AppendLine($"        public static {model.ClassName} Decode(ref ProtoReader reader)").AppendLine("        {");
        foreach (LogicalField field in model.Fields) AppendCSharpRead(code, field);
        code.AppendLine($"            return new {model.ClassName}({string.Join(", ", model.Fields.Select(field => Camel(field.Name)))});");
        code.AppendLine("        }").AppendLine("    }").AppendLine("}");
        return code.ToString();
    }

    public static string GenerateClientTable(ConfigOutputModel model, string rootNamespace, string recordNamespace)
    {
        string namespaceName = $"{rootNamespace}.{Sanitize(model.SheetName)}";
        string configNamespace = $"{recordNamespace}.{Sanitize(model.SheetName)}";
        StringBuilder code = Header();
        code.AppendLine("using System;").AppendLine("using GameProto;").AppendLine($"using {configNamespace};").AppendLine();
        code.AppendLine($"namespace {namespaceName}").AppendLine("{");
        code.AppendLine($"    public sealed class {model.ClassName}Table : ConfigTable<{model.ClassName}>").AppendLine("    {");
        code.AppendLine($"        private {model.ClassName}Table(int capacity)").AppendLine("            : base(capacity)").AppendLine("        {").AppendLine("        }");
        code.AppendLine().AppendLine($"        public static {model.ClassName}Table Load(byte[] data)").AppendLine("        {");
        code.AppendLine("            if (data == null)").AppendLine("            {").AppendLine("                throw new ArgumentNullException(nameof(data));").AppendLine("            }");
        code.AppendLine().AppendLine("            var reader = new ProtoReader(data);").AppendLine("            ConfigFileHeader header = ConfigFileHeader.Decode(ref reader);");
        code.AppendLine($"            if (header.SchemaHash != {model.ClassName}.SchemaHash)").AppendLine("            {").AppendLine("                throw new ConfigSerializationException(\"配置 Schema Hash 不匹配。\");").AppendLine("            }");
        code.AppendLine().AppendLine("            if (header.RecordCount > int.MaxValue)").AppendLine("            {").AppendLine("                throw new ConfigSerializationException(\"配置记录数超出 int 范围。\");").AppendLine("            }");
        code.AppendLine().AppendLine($"            var table = new {model.ClassName}Table((int)header.RecordCount);").AppendLine("            for (int i = 0; i < (int)header.RecordCount; i++)").AppendLine("            {");
        code.AppendLine($"                {model.ClassName} item = {model.ClassName}.Decode(ref reader);").AppendLine($"                table.Add(item.{model.KeyFieldName}, item);").AppendLine("            }");
        code.AppendLine().AppendLine("            reader.EnsureFullyConsumed();").AppendLine("            return table;").AppendLine("        }").AppendLine("    }").AppendLine("}");
        return code.ToString();
    }

    public static string GenerateGo(ConfigOutputModel model, string packageName)
    {
        StringBuilder code = new();
        code.AppendLine("// Code generated by ConfigTableGenerator. DO NOT EDIT.").AppendLine($"package {packageName}").AppendLine();
        foreach (LogicalField field in model.Fields.Where(field => field.Type.Kind == ConfigTypeKind.Custom))
        {
            code.AppendLine($"type {field.Type.Name} struct {{");
            foreach (ConfigMember member in field.Type.Members) code.AppendLine($"\t{member.Name} {GoType(member.Type)}");
            code.AppendLine("}").AppendLine();
        }
        code.AppendLine($"const {model.ClassName}SchemaHash uint64 = 0x{SchemaHashValue(model):X16}").AppendLine();
        code.AppendLine($"type {model.ClassName} struct {{");
        foreach (LogicalField field in model.Fields) code.AppendLine($"\t{field.Name} {GoType(field.Type)}");
        code.AppendLine("}").AppendLine();
        code.AppendLine($"func Decode{model.ClassName}(reader *Reader) (*{model.ClassName}, error) {{").AppendLine($"\tvalue := &{model.ClassName}{{}}").AppendLine("\tvar err error");
        foreach (LogicalField field in model.Fields) AppendGoRead(code, field);
        code.AppendLine("\treturn value, nil").AppendLine("}");
        return code.ToString();
    }

    private static void AppendCSharpCustomTypes(StringBuilder code, IEnumerable<LogicalField> fields)
    {
        foreach (LogicalField field in fields.Where(field => field.Type.Kind == ConfigTypeKind.Custom))
        {
            code.AppendLine($"    public sealed class {field.Type.Name}").AppendLine("    {");
            foreach (ConfigMember member in field.Type.Members) code.AppendLine($"        public {CSharpType(member.Type)} {member.Name} {{ get; }}");
            code.AppendLine().AppendLine($"        public {field.Type.Name}({string.Join(", ", field.Type.Members.Select(member => $"{CSharpType(member.Type)} {Camel(member.Name)}"))})").AppendLine("        {");
            foreach (ConfigMember member in field.Type.Members) code.AppendLine($"            {member.Name} = {Camel(member.Name)};");
            code.AppendLine("        }").AppendLine("    }").AppendLine();
        }
    }

    private static void AppendCSharpRead(StringBuilder code, LogicalField field)
    {
        string variable = Camel(field.Name);
        if (field.Type.Kind == ConfigTypeKind.Scalar)
        {
            code.AppendLine($"            {CSharpType(field.Type)} {variable} = reader.{CSharpReader(field.Type)}();");
        }
        else if (field.Type.Kind is ConfigTypeKind.Array or ConfigTypeKind.List)
        {
            code.AppendLine($"            int {variable}Count = reader.ReadCollectionCount();");
            string allocation = field.Type.Kind == ConfigTypeKind.Array ? $"new {CSharpType(field.Type.ElementType!)}[{variable}Count]" : $"new List<{CSharpType(field.Type.ElementType!)}>({variable}Count)";
            code.AppendLine($"            {CSharpType(field.Type)} {variable} = {allocation};").AppendLine($"            for (int i = 0; i < {variable}Count; i++)").AppendLine("            {");
            string read = $"reader.{CSharpReader(field.Type.ElementType!)}()";
            code.AppendLine(field.Type.Kind == ConfigTypeKind.Array ? $"                {variable}[i] = {read};" : $"                {variable}.Add({read});");
            code.AppendLine("            }");
        }
        else
        {
            foreach (ConfigMember member in field.Type.Members) code.AppendLine($"            {CSharpType(member.Type)} {variable}{member.Name} = reader.{CSharpReader(member.Type)}();");
            code.AppendLine($"            {field.Type.Name} {variable} = new {field.Type.Name}({string.Join(", ", field.Type.Members.Select(member => variable + member.Name))});");
        }
    }

    private static void AppendGoRead(StringBuilder code, LogicalField field)
    {
        if (field.Type.Kind == ConfigTypeKind.Scalar)
        {
            AppendGoAssignment(code, $"value.{field.Name}", field.Type, 1);
        }
        else if (field.Type.Kind is ConfigTypeKind.Array or ConfigTypeKind.List)
        {
            string count = Camel(field.Name) + "Count";
            code.AppendLine($"\t{count}, err := reader.ReadCollectionCount()").AppendLine("\tif err != nil {").AppendLine("\t\treturn nil, err").AppendLine("\t}");
            code.AppendLine($"\tvalue.{field.Name} = make({GoType(field.Type)}, {count})").AppendLine($"\tfor i := range value.{field.Name} {{");
            AppendGoAssignment(code, $"value.{field.Name}[i]", field.Type.ElementType!, 2);
            code.AppendLine("\t}");
        }
        else
        {
            foreach (ConfigMember member in field.Type.Members) AppendGoAssignment(code, $"value.{field.Name}.{member.Name}", member.Type, 1);
        }
    }

    private static void AppendGoAssignment(StringBuilder code, string target, ConfigType type, int indent)
    {
        string tabs = new('\t', indent);
        code.AppendLine($"{tabs}{target}, err = reader.{GoReader(type)}()").AppendLine($"{tabs}if err != nil {{").AppendLine($"{tabs}\treturn nil, err").AppendLine($"{tabs}}}");
    }

    private static StringBuilder Header() => new("// <auto-generated />\n");
    private static ulong SchemaHashValue(ConfigOutputModel model) => BinaryPrimitives.ReadUInt64LittleEndian(SchemaHash.Compute(model));
    private static string Camel(string value) => char.ToLowerInvariant(value[0]) + value[1..];
    private static string Sanitize(string value) => new(value.Select(character => char.IsLetterOrDigit(character) || character == '_' ? character : '_').ToArray());
    private static string CSharpType(ConfigType type) => type.Kind switch { ConfigTypeKind.Array => CSharpType(type.ElementType!) + "[]", ConfigTypeKind.List => $"List<{CSharpType(type.ElementType!)}>", ConfigTypeKind.Custom => type.Name, _ => type.Name };
    private static string GoType(ConfigType type) => type.Kind is ConfigTypeKind.Array or ConfigTypeKind.List ? "[]" + GoType(type.ElementType!) : type.Kind == ConfigTypeKind.Custom ? type.Name : type.Name switch { "int" => "int32", "uint" => "uint32", "long" => "int64", "float" => "float32", "double" => "float64", _ => type.Name };
    private static string CSharpReader(ConfigType type) => type.Name switch { "bool" => "ReadBoolean", "int" => "ReadInt32", "uint" => "ReadUInt32", "long" => "ReadInt64", "float" => "ReadSingle", "double" => "ReadDouble", "string" => "ReadString", _ => throw new InvalidDataException(type.Name) };
    private static string GoReader(ConfigType type) => type.Name switch { "bool" => "ReadBoolean", "int" => "ReadInt32", "uint" => "ReadUInt32", "long" => "ReadInt64", "float" => "ReadFloat32", "double" => "ReadFloat64", "string" => "ReadString", _ => throw new InvalidDataException(type.Name) };
}
